language: go

go:
  - "1.14.x"
  - "1.15.x"
  - "master"  # find out if an upcoming change in Go is going to break us

matrix:
  # We only want to fail the build based on stable versions of Go
  allow_failures:
    - go: master
  fast_finish: true

# No need for an install step as all dependencies are vendored.
install: []

script:
  - ./runtests -r small medium large
  - ./perfcheck small medium large

env:
  global:
    secure: MpOY0NYnuf8hgDVP4MjSSrrzWDdPlJ5JnB/TiiJxptjN2qn0OKPVBeZl2OsJ3MlZfjNM3wZ3mNN6p/3TwJmfp1g+3SU9MfRul4XMFfJKiN9u5/y5lamophs+vkgrawG00xwMd4KvKOqXVP2vX2s+koVfUzUXEot5IJDMerQltQPqbonvk/tWJHmtu5NoMQgGO+2pvmy+74u5HMfjoWSmTBiJgTUZ8c/a1nK3MsG2mafsEB8sLa8uMWAp9ISnfxLzTTUFQeVR64i1z7duz5fJ0B96JqYIlwnR9vzeB1gr+3+cSdDUPfcTgWEDhDn9Kglqe71K+9vUaP3cOkEMThFPoj1wb2vyIV2LYVqsAVAmxBFiyMS8HVkp7z0M7f34wRhd3blN2KaxYuiFlSg3MwnUp615NHnnS8kA0So/E7xYcXnsfFx9f1ZZqaAuHz1DrD2UHeRKtcekdcxTMG4LMJbGv+HsqL6mUFIND/tN9h/QV+w+GbmKUUBt/xMmyoaLqBwKz+m1aLvBSZ9IaUIHRKCNnCfm9QPXoMfeXvh2JCX7leM/0FDHUp8v1J1Rw5E0eiWpBS0OlQS2OeR8zAlJh8mZ4SpApUEHDEHBbcVSP0ZM+fSMpq1OVESlmEO308WZY0IlmQ9UkDIpixLuizDB4IlwOPVXlRSyHd9spAmqx4ZGfR4=

notifications:
  slack:
    secure: Py9Z8gyzsr63Wx8+GZNluL18Npf1y08K4IqtODK7jb9bRddyrsEwjFrqCE8KGNfgbYc1h9UAE2MXEbX2vtF3nTrBHUzo8m15c9bKNlc5SJQO40B4+fu/xfzUn+XdDCaZyoaMBSUOrIJwTfFrPPWzfAa7g13xIXMk7Pa/bKAlkj+gFKhvHCf2JCf3sUSaZ+2/A4py9S5ljfAMYhk48XTKqODAZGnpRkgPnKRYvIBKrWGXhS8V++UHcR19Dng1ND+3y/t5mtjZuvSSm5e1EN0kjNVhhsCmZPBjeQUg17YbuzCh7qVCxI5clseAlaAx3MdImhiSCo44rgJ8oYpSR9I2MwN9wYL9h0aZ/V1vEUPZ9vyRRVe09T1MGsKMMrcSMflplV/vEk/v8eo2PC+tU+NfTyJd6dQ0eMF5SjOrUL2mOp0vxS6fGc+D8y1Lni/rrm9huGKPIKarzqBpye22npBm2OxYBgl9gZoGRzyZtyyTYBxp2PgcirfEbcM+UPoFC2cgRwfV5TacYaJfU6Jel+lmCyLbPzE/0ZXeQ/xNH4sWVhuGjYJj4t+cHNxhk4HDlza6eOXeh7feO8tivBcwO8+JWhNt0zzNWW+Nvu9XcFMtVhjaIwQh7A5w0AVtUs17dnbDcURvDSBjrh9WELFxE9gLB8uF52VQO6/FpnaQ6EWsIFg=

# Create release tarball and publish to Github using GoReleaser.
# Releases are only built with a specific Go version and only if a tag
# is set.
deploy:
- provider: script
  skip_cleanup: true
  script: make release
  on:
    tags: true
    go: "1.11.2"
